name: Update gist
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.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 }}
          GIST_ID: ${{ secrets.gist:aca45d20bb2dab0aef89061252771565 }}
          TIMEZONE: Asia/Seoul
